name: Test CI
on:
  push:

  pull_request:
    branches:
      - master
      - main

  schedule:
    - cron: 0 2 * * 0

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [ '16' ]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - run: npm run build

